### PR TITLE
大谷秀瑜

### PR DESCRIPTION
**Pull request by siouyu**
十分抱歉未能在昨日 23:50 前繳交，以下是我的上週作業，希望能請老師檢查，謝謝🙏

http://3.130.219.42:3000/
http://3.130.219.42:3000/attraction/8

跳出視窗的右上角我沒有放 x 按鍵，而是當使用者點擊頁面其他地方、以及偵測到使用者往下滾動頁面時，跳出視窗就會自動關閉。這樣使用者就不用特別移動手指去按 x 按鍵，我覺得這樣會更方便一些。

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Use password input element for password input.
2. We should call **get current user API** to check user sign-in status.
3. Don't refresh page if there is error on sign in/sign up procedure.

**Comment by siouyu** [comment]
> 1. Use password input element for password input.
> 2. We should call **get current user API** to check user sign-in status.
> 3. Don't refresh page if there is error on sign in/sign up procedure.

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should call **get current user API** to check user sign-in status, not just depend on token in localStorage.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
